// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// stratified_train_test_split
List stratified_train_test_split(NumericMatrix X, IntegerVector y, double test_ratio);
RcppExport SEXP _SA24204129_stratified_train_test_split(SEXP XSEXP, SEXP ySEXP, SEXP test_ratioSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type test_ratio(test_ratioSEXP);
    rcpp_result_gen = Rcpp::wrap(stratified_train_test_split(X, y, test_ratio));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SA24204129_stratified_train_test_split", (DL_FUNC) &_SA24204129_stratified_train_test_split, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SA24204129(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
